### ISSUE TITLE
多个使用时，手动连线只有最新的可以，其他的不行

### ISSUE THREAD

**Issue by huiery** [zsjjs/react-field-mapping#13]
使用场景：在不同tab中使用react-field-mapping
操作：tab1使用mapping1，tab2使用mapping2，新增tab3使用组件mapping3时，
问题：mapping3手动连线和同行连线等均可使用；
           mapping1、mapping2手动连线不可用，其他同行连线可用
期望：mapping1、mapping2仍然可以手动连线

**Comment by shaojun427** [comment]
其实连线都在的，只是位置不对了，因为组件本身在初始化渲染时有一个布局的位置定位，用的是dom的offset属性来获取的，连线的位置都是基于这个布局的定位来画的。
但是antd的tab组件有一个问题，他们在切换的时候，会先把content的组件渲染，再去做那个移动的动画（用的是margin-left属性，BFC影响offset属性），组件再渲染的时候获取到的offset就会是移动前的位置，导致了这个误差，现在的解决办法只能是使用组件的时候，写一个判断或者延时，等移动完了再去渲染组件就可以了

补充： 发现现在的初始化获取一次布局位置的机制，不太友好，一个解法就是每次组件所在布局出现位置有移动后，都要重新渲染组件才行。所以后面组件会增加一个在连线的时候重新获取布局位置的逻辑来解决这个问题。请等待1.0.4版本完善这个问题

**Comment by shaojun427** [comment]
1.0.4 fixed

**Comment by huiery** [comment]
你好，请问下为什么1.0.4版本的安装不下来，报包不存在的错误



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jason zhou <notifications@github.com&gt;
发送时间: 2019年11月23日 00:15
收件人: zsjjs/react-field-mapping <react-field-mapping@noreply.github.com&gt;
抄送: huiery <1020133587@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zsjjs/react-field-mapping] 多个使用时，手动连线只有最新的可以，其他的不行 (#13)




Closed #13.

**Comment by shaojun427** [comment]
> 你好，请问下为什么1.0.4版本的安装不下来，报包不存在的错误发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: jason zhou <notifications@github.com&gt; 发送时间: 2019年11月23日 00:15 收件人: zsjjs/react-field-mapping <react-field-mapping@noreply.github.com&gt; 抄送: huiery <1020133587@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[zsjjs/react-field-mapping] 多个使用时，手动连线只有最新的可以，其他的不行 (#13) Closed #13. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我尝试npm和yarn都是可以的，你看看是不是包的名字弄错了
npm i react-field-mapping@latest -S
yarn add react-field-mapping@latest -S

**Comment by huiery** [comment]
我是用cnpm的命令最新的都是1.0.3版本的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jason zhou <notifications@github.com&gt;
发送时间: 2020年1月3日 10:31
收件人: zsjjs/react-field-mapping <react-field-mapping@noreply.github.com&gt;
抄送: huiery <1020133587@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zsjjs/react-field-mapping] 多个使用时，手动连线只有最新的可以，其他的不行 (#13)



 
你好，请问下为什么1.0.4版本的安装不下来，报包不存在的错误发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: jason zhou <notifications@github.com&gt; 发送时间: 2019年11月23日 00:15 收件人: zsjjs/react-field-mapping <react-field-mapping@noreply.github.com&gt; 抄送: huiery <1020133587@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[zsjjs/react-field-mapping] 多个使用时，手动连线只有最新的可以，其他的不行 (#13) Closed #13. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我尝试npm和yarn都是可以的，你看看是不是包的名字弄错了
 npm i react-field-mapping@latest -S
 yarn add react-field-mapping@latest -S

**Comment by shaojun427** [comment]
我cnpm (v6.1.0)的也试了 ，可以啊cnpm i react-field-mapping@latest -S
![image](https://user-images.githubusercontent.com/16127112/71711748-658f6300-2e3d-11ea-881d-ca9cbcfab4bd.png)
