### ISSUE TITLE
OnChange suggestion

### ISSUE THREAD

**Issue by chungchi300** [zsjjs/react-field-mapping#19]
Hi zsjjs, great library there, some problem it has when I have a function like
```
  if (isMultipleSourceToOneTargetThatIsAcceptable(relation)) {
              console.log("new");
              this.setState({
                relation
              });
            } else {
                  }
```
 but I discover it still chang even I am not setting that, is it an uncontrolled component?

**Comment by chungchi300** [comment]
what my existing solution
```javascript
onDrawEnd: (source, target, relation) => {
            this.previousRelation = _.cloneDeep(this.state.relation);
          },
          onChange: relation => {
            if (isMultipleSourceToOneTargetThatIsAcceptable(relation)) {
              console.log("new");
              this.setState({
                relation
              });
            } else {
              this.setState({
                relation: this.previousRelation
              });
            }
          },
```

**Comment by shaojun427** [comment]
The design of relation is an uncontrolled property, but when the component is used, relation props will trigger the component's update to change the internally maintained relation.
![image](https://user-images.githubusercontent.com/16127112/76717509-9d385680-676e-11ea-837d-b20caac50cb7.png)

**Comment by shaojun427** [comment]
At present, if you want to get the latest relation, you can follow the method in the demo. Later, the current relation will be split into a controlled relation and a defaultRelation.

**Comment by shaojun427** [comment]
Your requirement is to map multiple sources to one target. This is controlled by api. This api exists in v1.0.5 and later
![image](https://user-images.githubusercontent.com/16127112/76720514-01134d00-6778-11ea-9b76-8fb23f69a799.png)

**Comment by shaojun427** [comment]
This api exists in v1.0.5 and later

**Comment by chungchi300** [comment]
thanks for the quick reply, but in my current problem is I only want only one of the target can be connected by 1 source instead of multiple

**Comment by shaojun427** [comment]
The default is one-to-one. Only the source in the demo has the multiple attribute set.
Do you want this effect：https://codepen.io/godIsMe/pen/gOpKmEo?editors=1010
