### ISSUE TITLE
内容区滚动时（不是body滚动），联线出现异常

### ISSUE THREAD

**Issue by aisriver** [zsjjs/react-field-mapping#2]

**Comment by shaojun427** [comment]
希望有复现demo

**Comment by aisriver** [comment]
https://codepen.io/godIsMe/pen/NEOdXJ
左边dom改成这个，滚动到下面，然后添加联线试试
id="Test" style="height: 200px; overflow-y: scroll;"

<div id="Test" style="height: 200px; overflow-y: scroll;"></div>

**Comment by aisriver** [comment]
“<div id="Test" style="height: 200px; overflow-y: scroll;"></div>”

**Comment by aisriver** [comment]
id="Test" style="height: 200px; overflow-y: scroll;"

**Comment by shaojun427** [comment]
[https://github.com/zsjjs/react-field-mapping/commit/97a327bea2d811e378b1eb4373bbaf931d60273b](url)
