### ISSUE TITLE
Invalid mapping relation error

### ISSUE THREAD

**Issue by shanmugarajbe** [zsjjs/react-field-mapping#25]
Hey 
Features are really cool. 
Found an issue where if there is any invalid key values in the `relation` , then arrow is displaying by connecting first source row to first target row. 

`this.state = {
      relation: [{
        source: {
          key: "Nofield"
        },
        target: {
          key: "field502"
        }
      }]}`

shows connecting arrow between first source row and first target row like below,
![image](https://user-images.githubusercontent.com/8328633/94057391-2e167b80-fdfd-11ea-9e69-fb8e60c9a625.png)

**Comment by shaojun427** [comment]
Thank you very much for informing about this problem, it has been fixed in v1.1.4
