### ISSUE TITLE
option中的onChange，在初始化的时候会默认执行一次

### ISSUE THREAD

**Issue by aisriver** [zsjjs/react-field-mapping#4]
在做事件绑定的时候有可能引起死循环

**Comment by aisriver** [comment]
太感谢啦！另外，有时候字段映射会要求显示更多信息的情况，所以可以考虑加一下多表头配置。

**Comment by shaojun427** [comment]
onchange是在changeRelation的时候触发的，如果有加初始属性relation，那么就会触发一次onChage

**Comment by shaojun427** [comment]
> 太感谢啦！另外，有时候字段映射会要求显示更多信息的情况，所以可以考虑加一下多表头配置。

这个多表头是什么意思？？现在是就两张表，表头都能自己配置，但是里面就类型和字段名两列，你的需求是除了字段名和类型 要增加字段的列？？

**Comment by aisriver** [comment]
> > 太感谢啦！另外，有时候字段映射会要求显示更多信息的情况，所以可以考虑加一下多表头配置。
> 
> 这个多表头是什么意思？？现在是就两张表，表头都能自己配置，但是里面就类型和字段名两列，你的需求是除了字段名和类型 要增加字段的列？？

对，这样的话拓展性会比较高了，就像普通table的渲染一样，提供cell或render方法。增加、删除等操作就可以让我们自定义了。

**Comment by aisriver** [comment]
> onchange是在changeRelation的时候触发的，如果有加初始属性relation，那么就会触发一次onChage

我觉得onchange和onRelationChange可以区分一下，前者是手动触发，后者是监听，这样用起来可能更方便。否则我仍然需要在设置默认值的时候去判断一下是否要更新数据，而不会出现死循环。

**Comment by shaojun427** [comment]
@aisriver 基于你之前提的优化已经发了一个大版本了，你可以先用下看看
https://www.npmjs.com/package/react-field-mapping
demo里面有用法，有几个api和之前的不一样了

**Comment by shaojun427** [comment]
#6

**Comment by aisriver** [comment]
> @aisriver 基于你之前提的优化已经发了一个大版本了，你可以先用下看看
> https://www.npmjs.com/package/react-field-mapping
> demo里面有用法，有几个api和之前的不一样了

非常棒！！不过我还有个建议，拖拽行上下排序的时候，会自动取消之前的联线，这个后面也可以优化一下。
